export const procastinationData = {
  src: "https://theuselessweb.com/",
  urls: [
    "https://playsnake.org/",
    "https://neave.com/swarm/",
    "http://endless.horse/",
    "https://worlds-highest-website.com/",
    "http://tinytuba.com/",
    "http://www.staggeringbeauty.com/",
    "http://eelslap.com/",
    "http://www.koalastothemax.com/",
    "https://thatsthefinger.com/",
    "http://www.rrrgggbbb.com/",
    "http://www.fallingfalling.com/",
    "http://chrismckenzie.com/",
    "https://cat-bounce.com/",
    "https://pointerpointer.com/",
    "http://www.yesnoif.com/",
    "http://www.crossdivisions.com/",
    "http://intotime.com/",
    "http://www.patience-is-a-virtue.org/",
    "http://pixelsfighting.com/",
    "http://onemillionlols.com/",
    "https://www.omfgdogs.com/",
    "http://chihuahuaspin.com/",
    "http://www.blankwindows.com/",
    "http://www.ascii-middle-finger.com/",
    "http://spaceis.cool/",
    "http://www.trashloop.com/",
    "http://yeahlemons.com/",
    "http://dogs.are.the.most.moe/",
    "https://hooooooooo.com/"
  ]
};
